name: PHPStan

on:
  push:
    branches:
      - 4.2.x
  pull_request:

jobs:
  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G
